"""Export the backtest trades + price data into a single .sql file
that you can run directly against MySQL / PostgreSQL / SQLite."""
import pandas as pd

def esc(v):
    if pd.isna(v):
        return "NULL"
    if isinstance(v, str):
        return "'" + v.replace("'", "''") + "'"
    if hasattr(v, "date"):
        return "'" + str(pd.to_datetime(v).date()) + "'"
    return str(v)

def main():
    trades = pd.read_csv("trades.csv")
    prices = pd.read_csv("price_data.csv")

    with open("ratio_strategy.sql", "w") as f:
        f.write("-- =====================================================\n")
        f.write("-- Sensex-Nifty Ratio Spread Strategy : trades + prices\n")
        f.write("-- Generated by backtest.py\n")
        f.write("-- =====================================================\n\n")

        # ---- price_data table ----
        f.write("DROP TABLE IF EXISTS price_data;\n")
        f.write("""CREATE TABLE price_data (
    trade_date    DATE PRIMARY KEY,
    sensex_close  DECIMAL(12,2),
    nifty_close   DECIMAL(12,2)
);\n\n""")
        for _, r in prices.iterrows():
            f.write(f"INSERT INTO price_data (trade_date, sensex_close, nifty_close) "
                    f"VALUES ({esc(r.date)}, {r.sensex_close}, {r.nifty_close});\n")

        # ---- trades table ----
        f.write("\n\nDROP TABLE IF EXISTS trades;\n")
        f.write("""CREATE TABLE trades (
    trade_id      INTEGER PRIMARY KEY,
    entry_date    DATE,
    exit_date     DATE,
    direction     VARCHAR(12),   -- LONG_SPREAD = buy Sensex/sell Nifty
    spread_type   VARCHAR(8),    -- credit / debit
    sensex_entry  DECIMAL(12,2),
    nifty_entry   DECIMAL(12,2),
    ratio         DECIMAL(6,3),
    spread_entry  DECIMAL(12,2),
    zscore_entry  DECIMAL(8,3),
    sensex_exit   DECIMAL(12,2),
    nifty_exit    DECIMAL(12,2),
    spread_exit   DECIMAL(12,2),
    zscore_exit   DECIMAL(8,3),
    holding_days  INTEGER,
    pnl_points    DECIMAL(12,2),
    pnl_inr       DECIMAL(14,2),
    exit_reason   VARCHAR(16)
);\n\n""")
        cols = ["entry_date","exit_date","direction","spread_type","sensex_entry",
                "nifty_entry","ratio","spread_entry","zscore_entry","sensex_exit",
                "nifty_exit","spread_exit","zscore_exit","holding_days",
                "pnl_points","pnl_inr","exit_reason"]
        for i, r in trades.iterrows():
            vals = ", ".join(esc(r[c]) for c in cols)
            f.write(f"INSERT INTO trades (trade_id, {', '.join(cols)}) "
                    f"VALUES ({i+1}, {vals});\n")

        # ---- handy analysis views ----
        f.write("\n\n-- Quick performance check:\n")
        f.write("""-- SELECT COUNT(*) AS trades,
--        ROUND(SUM(pnl_points),2) AS total_pts,
--        ROUND(AVG(pnl_points),2) AS avg_pts,
--        ROUND(100.0*SUM(CASE WHEN pnl_points>0 THEN 1 ELSE 0 END)/COUNT(*),1) AS win_rate
-- FROM trades;\n""")

    print("Wrote ratio_strategy.sql")

if __name__ == "__main__":
    main()
